name: Release

on:
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Run Build
      run: ./build.sh
      working-directory: go
        
    - name: Upload assets
      uses: actions/upload-artifact@v2
      with:
        name: coding-badly-relay-wasm
        path: go/out/*
